name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated from v2 to v4

      - name: Set Up Java
        uses: actions/setup-java@v3  # Updated from v2 to v3
        with:
          distribution: 'temurin'  # Use OpenJDK
          java-version: '17'  # Set Java version

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Run Tests with Maven
        run: mvn test
        working-directory: BlockDAG-Automation  # Ensure this is the correct path to your `testng.xml`

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Test Report
          path: BlockDAG-Automation/test-output/emailable-report.html  # Ensure the correct report path
