name: Run TestNG Tests and Generate Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Java JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Install dependencies (e.g., Maven)
      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Run Maven test to execute TestNG tests
      - name: Run Tests
        run: |
          mvn clean test -DsuiteXmlFile=testng.xml

      # Upload the emailable report as an artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: emailable-report
          path: test-output/emailable-report.html
